config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  devise_for :users
  resources :users
  
  resources :posts do
  	resources :reviews
  end
 
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :reviews
	scope :most_recent_four, -> { all.limit(4) }
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name << :username
    devise_parameter_sanitizer.for(:account_update)  << :first_name << :last_name << :username
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index


    @posts = if params[:search]
        Post.where("LOWER(title) LIKE LOWER(?)", "%#{params[:search]}%")
      else
        Post.all
      end

       @posts = @posts.order(created_at: :desc).page(params[:page])
       @most_recent_four = Post.most_recent_four
       
      respond_to do |format|
        format.html
        format.js
      end
  end

  def new
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post = Post.find(params[:id])
     @review = @post.reviews.build
     @most_recent_four = Post.most_recent_four
     @reviews =  @post.reviews.all
  end

  # GET /posts/new
  

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :content)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_filter :load_post
  before_filter :ensure_logged_in

  def index
     @reviews = Review.all
  end

  def show
  end

  def new
    @post = Post.find(params[:post_id])
    @review = @post.reviews.build(review_params)
  end


  def create
  	@review = @post.reviews.build(review_params)
  	@review.user_id = current_user.id

    respond_to do |format|
    	if @review.save
    		format.html {redirect_to post_path(@post), notice: "Thank you for your review"}
   	    format.js  
      else
   		  format.html { render 'posts/show', alert: 'Error'}   
    	  format.js
      end
    end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  	redirect_to posts_path
  end



  def load_post
  	@post= Post.find(params[:post_id])
  end

  private

  def set_review
      @review = Review.find(params[:id])
  end


  def review_params
  	params.require(:review).permit(:comment, :post_id, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    private
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :username, :password, :password_confirmation)
    end
  
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
 <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to 'Blog', root_url %></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li><a  href="#" title="contact" data-reveal-id="contact_us">Contact</a></li>
        
              <% if current_user %>
                <li class="signed_in"><%= link_to "Signed in as #{current_user.first_name}", user_path(current_user) %></li>
                <li><%= link_to "Profile Settings", user_path(current_user) %></li>
                <li><%= link_to "Sign Out!", destroy_user_session_url, method: :delete %></li>
              <% else %>
                <li><%= link_to "Log In",  new_user_session_path %></li>
                
                <li><%= link_to "Sign Up!", new_user_registration_path,  id: "btn_signup" %></li>
                
              <% end %>
            
          </ul>

          <!-- Left Nav Section -->
          <ul class="left menu">
            <li><a href="#" title="about">About</a></li>
          </ul>
        </section>
      </nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/_panel.html.erb
<div id="contact_us" class="reveal-modal medium" data-reveal>

    <div class="row">
        <div class="large-6">
          <h2>Contact Us</h2>
        </div>
    </div><br>

     <form>
        <div class="row">
          <div class="large-6 columns input">
            <label><i class="fi-torso"></i> Name
              <input type="text" placeholder="Name" class="radius"/>
            </label>
          </div>
        
          <div class="large-6 columns input">
            <label><i class="fi-mail"></i>Email
              <input type="email" placeholder="Email" class="radius" />
            </label>
          </div>
        </div>

         <div class="row">
          <div class="large-12 columns input">
          <label>Message
            <textarea rows="6"></textarea>
          </label>
        </div>
         </div>

          <div class="row">
            <div class="large-12 columns">
             <input type="submit" value="Send!" class="button secondary tiny radius right"/>
            </div>
          </div>

          </form>
    <a class="close-reveal-modal">&#215;</a>
    </div>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

   <div class="container">

        <header>
          <%= render 'layouts/navigation' %>
        </header>
          <%= render 'layouts/panel' %>

        <main role="main">
           
          <%= render 'layouts/messages' %>
           
          <%= yield %>

             
          <footer class="text-center">
            <hr>
            <small>&copy; 2014 - All Right Reserved</small>

          </footer>

        </main>
    
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button right radius' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
 <tr>
      <td><%= post.created_at.strftime("%d %b. %Y") %></td>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%=  post.author %></td>
      <td><%= truncate(post.content, :length =>50) %></td>
    </tr>

app/views/posts/_sidebar.html.erb
<div class="sidebar large-4 columns">
  <h2>&nbsp</h2><hr>
  

    <div class="row">
      <h4 class="text-right">New!</h4>
        <div class="blog large-12 columns">
          
         
           <ul class="example-orbit-content" data-orbit data-options="pause_on_hover:true;animation_speed:500; navigation_arrows:true;bullets:false;">

            <% @most_recent_four.each do |new_post| %>
            <li data-orbit-slide="headline-1">
              <div>
                   <h3><%= new_post.title %></h3><hr>

                    <h6 class="subheader">
                      <%= truncate(new_post.content, :length =>90) %>es ornare tempor...
                    </h6>  
               
               <%= link_to 'Read More', post_path(new_post), class: 'button tiny radius right' %>
               <br>         
              </div>
            </li>
               <% end %>
          </ul>

        
        </div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="margin40"></div>
<div class="row">

  <div class="row">

      <div class="medium-4 columns">
       
        <%= form_tag posts_path, method: :get, authentication: false, id: 'search-form' do %>

      <div class="row">

        <div class="medium-10 columns">
          <%= text_field_tag :search, params[:search], value: 'Search Posts' %>
        </div>
        <div class="medium-2 medium-pull-1 columns">
          <%= submit_tag "Search", class: 'button tiny radius search' %>
          </div>
        </div>
        <% end %>

      </div>

  </div>

 
     <div class="large-8 columns">


      <h2>All Posts<span><%= link_to  'Add Post', new_post_path, class: 'button tiny radius right'%></span></h2><hr>
        <table>
  <thead>
    <tr>
      <th width="150">Date</th>
      <th>Title</th>
      <th width="100">Author</th>
      <th width="300">Post</th>

    </tr>
  </thead>
  <tbody>
      <%= render @posts %>
  </tbody>
</table>

<div id="paginate">
  <%= paginate @posts, :window => 2 %>
</div>


</div>
 

<%= render 'sidebar' %>

    </div><!-- row --><br>


<hr>

 <div class="row">

        <div class="newsletter large-12 columns">
          <h4>Sign Up to our Newsletter</h4>
          <div class="panel callout">
         
           <form>
            <div class="row">
              <div class="large-12 columns">
                <label>Email
                  <input type="text" placeholder="enter email" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">    
                  <input type="submit" class="button tiny right radius"/>   
              </div>
            </div>

          </form>
          </div>
        </div>  
      </div>

    </div><!-- row -->
  
  </div><!--sidebar-->

</div><!-- row -->

app/views/posts/index.js.erb
index.js.erb

app/views/posts/new.html.erb
<div class="row">
<div class="margin20"></div>

	<div class="medium-6 medium-offset-3 columns">
	<%= link_to 'Back', posts_path, class: 'button radius tiny' %>
		<h1>New post</h1>

		<%= render 'form' %>


	</div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">


     <div class="post large-8 columns">

      <div class="links">
      	<%= link_to  'All Posts', posts_path, class: 'button tiny radius'%>

      	<%= link_to  'Add a Post', new_post_path, class: 'button tiny radius'%>
     
      </div>


      <h2>&nbsp</h2>
      <hr>
      <h2>Post - title</h2>
      <p><strong>Date:</strong> 2014, Jul 13  -  <strong>Author:</strong> John Doe </p>
      <hr>
      <br>

      <p class="text-justify"><span class="indent"></span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


      <div class="row">


        <div class="medium-12 columns">

            <a href="" id="review" class="button round tiny right">Add Review</a>

            <div class="margin"></div>
            <hr>

              <div data-alert class="alert-box alert_review alert round">
                 Oops! some Information is missing
                  <a href="#" class="close">&times;</a>
              </div>

                <div data-alert class="alert-box notice_review success round">
                 Thank You for your review
                  <a href="#" class="close">&times;</a>
              </div>


            <div id="review_form">

            <% if current_user %>
    
               <%= render 'reviews/form' %>

            <% else %>
                <p>please <%= link_to 'log in', new_user_session_path %>  to add a review</p>
            <% end %>

            </div> <!-- review_form --> 

        </div>
        <div class="clearfix"></div>


        <div class="large-12  columns panel" id="reviews">
      
          <h3>Reviews</h3>

          <div id="review-list">
            <%= render @post.reviews %>
          </div>
        </div>  


      </div><!-- row  -->

      
  </div>
 

<%= render 'sidebar' %>

    </div><!-- row --><br>


<hr>

 <div class="row">

        <div class="newsletter large-12 columns">
          <h4>Sign Up to our Newsletter</h4>
          <div class="panel" id='reviews'>
         
           <form>
            <div class="row">
              <div class="large-12 columns">
                <label>Email
                  <input type="text" placeholder="enter email" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">    
                  <input type="submit" class="button tiny right radius"/>   
              </div>
            </div>

          </form>
          </div>
        </div>  
      </div>

    </div><!-- row -->
  
  </div><!--sidebar-->

</div><!-- row -->

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/reviews/_form.html.erb
<%= form_for([@post, @review], remote: true) do |f| %>
        <% if @review.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

            <ul>
            <% @review.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field row">
          <div class="large-12 columns">
            <%= f.label :comment %>
            <%= f.text_area :comment, rows: '4', id: 'review_comment' %>
          </div>    
        </div><br>

        <div class="actions">
          <%= f.submit class: 'button small tiny radius right', value: "Add Review", id: 'review_form_btn' %>
        </div>  
      <% end %>

app/views/reviews/_review.html.erb
    <% if !review.user.nil? %>
  
        <p><img class="th" src="http://placehold.it/50x50/&text=avatar"><br><em>
        <%= review.user.username %></em><br><span>Added on:  <%= review.created_at %></span>
        </p>
        <p><%= review.comment %></p>
     
   <% else %>

      <p>No review yet</p>


        <% if current_user %>
          <p><% link_to "Be the first to add a review", new_post_review_path(@post) %></p>
        <% end %>
    <% end %>
    <hr>

    

app/views/reviews/create.js.erb
$('#review-list').prepend('<%= j(render @review)%>');

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/users/show.html.erb
<div class="row">
	<div class="medium-6 medium-offset-3 columns">
		<div class="margin20"></div>
		
		<ul>
			<li><%= @user.first_name %>, <%= @user.last_name %></li>
			<li>Username: <%= @user.username %></li>
			<li>Email: <%= @user.email %></li>
		</ul>
	</div>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>